### ISSUE TITLE
Do not limit number of episodes by default?

### ISSUE THREAD

**Issue by rfleschenberg** [richardcornish/django-itunespodcast#2]
Hi,

thanks for this package! It works nicely for me. One issue I have is that the feed only contains 50 episodes. Is there any particular reason for this limit?

**Comment by richardcornish** [comment]
No reason. It seemed like a large enough number, but there's no reason why this can't be a setting. Is that something you have a need for?

**Comment by rfleschenberg** [comment]
Yep. I am using your app for a podcast with currently ~130 episodes. I removed the limit by subclassing `ShowFeed`. I suggest not limiting by default and letting the user subclass (or maybe use a setting) if they want to limit the number of episodes. I think that typically, people will want to export all episodes in their feed.

**Comment by richardcornish** [comment]
Let me know how this update works for you. You can update with pip. Can I see the podcast you're doing? Just curious to see my work!

**Comment by rfleschenberg** [comment]
Thanks! I'll test it ASAP.

I'm not doing the podcast myself, I just provide the technical platform for the author. It's a faith-related thing in German, so the content might not be that interesting for you ;) It's on https://wunder-werke.de/podcast/ (we're working on getting it into itunes). As you can see, we are still using your default templates right now -- I still need to do customization and localization.

Cheers!

**Comment by richardcornish** [comment]
This looks awesome. If you have any suggestions for template improvements, I'm open to hearing those, too.
